'use client'
import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'tr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Çeviri objeleri
const translations = {
  en: {
    // Header
    home: 'Home',
    company: 'Company',
    products: 'Products',
    contact: 'Contact',
    getQuote: 'Get Quote',
    
    // Hero Section
    heroSubtitle: "Turkey's Only Iron Pyrite Lumps Producer",
    heroTitle1: 'Premium Industrial',
    heroTitle2: 'Minerals',
    heroDescription: 'Servicing raw materials industries with high-quality iron pyrite, olivine, manganese, and specialized minerals for steel mills and foundries worldwide.',
    exploreProducts: 'Explore Products',
    
    // Stats
    productLines: 'Product Lines',
    countriesServed: 'Countries Served',
    support: 'Support',
    
    // Features
    globalSupplyChain: 'Global Supply Chain',
    globalSupplyDesc: 'Complete supply chain management from mines to worldwide consumers',
    qualityAssured: 'Quality Assured',
    qualityAssuredDesc: 'IMMBI member with certified quality standards',
    strategicLocation: 'Strategic Location',
    strategicLocationDesc: 'Near Gemlik Port for optimized transportation',
    
    // Products Section
    ourProducts: 'Our Premium Products',
    productsDescription: 'High-quality industrial minerals sourced and processed to meet the demanding requirements of steel mills and foundries worldwide.',
    viewAllProducts: 'View All Products',
    learnMore: 'Learn More',
    
    // Company Section
    aboutNova: 'About Nova Minerals',
    companyDescription1: 'Nova Minerals is primarily dedicated to the sourcing and marketing of industrial minerals and materials, catering to the requirements of steel mills and foundries. Our comprehensive approach encompasses the entire supply chain, starting from our mining operations and extending to the global consumer market.',
    companyDescription2: 'The cornerstones of our interactions lie in open dialogue and transparency, forming the basis of our connections with both our sources and customers. We are proud to be Turkey\'s only Lumpy Iron Pyrite producer and a member of Istanbul Minerals Exporters\' Association (IMMBI).',
    learnMoreAbout: 'Learn More About Us',
    whyChooseNova: 'Why Choose Nova Minerals?',
    completeSupplyChain: 'Complete Supply Chain',
    completeSupplyDesc: 'From mining operations to global delivery',
    qualityAssurance: 'Quality Assurance',
    qualityAssuranceDesc: 'Certified standards and consistent quality',
    strategicLocationFull: 'Strategic Location',
    strategicLocationFullDesc: 'Near Gemlik Port for optimized logistics',
    dedicatedSupport: 'Dedicated Support',
    dedicatedSupportDesc: 'Single point of contact for all needs',
    
    // Footer
    footerDescription: 'Leading supplier of premium industrial minerals for steel mills and foundries worldwide. Turkey\'s only Iron Pyrite Lumps producer.',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
    quickLinks: 'Quick Links',
    footerCopyright: 'Nova Minerals. All rights reserved. | IMMBI Member',
    
    // Common
    available: 'Available',
    specifications: 'Specifications',
    applications: 'Applications',
    contactInfo: 'Contact Information',
    
    // Breadcrumb
    breadcrumbHome: 'Home',
    breadcrumbProducts: 'Products',
    breadcrumbCompany: 'Company',
    breadcrumbContact: 'Contact',

    // Product Names
    ironPyrite: 'Iron Pyrite',
    olivine: 'Olivine',
    manganese: 'Manganese',
    chromiteSand: 'Chromite Sand',
    sulphur: 'Sulphur',
    sodaAsh: 'Soda Ash',
    waterTreatment: 'Water Treatment',
    fluorspar: 'Fluorspar',

    // Product Descriptions
    ironPyriteDesc: "Turkey's only lumpy iron pyrite producer. Multiple size options from 75 micron to 100mm lumps.",
    olivineDesc: 'Premium quality olivine for foundry, blasting, refractory, and slag applications.',
    manganeseDesc: 'Various manganese compounds for metallurgical and chemical applications.',
    chromiteSandDesc: 'High-quality chromite sand for foundry applications with excellent surface finish.',
    sulphurDesc: 'Bright yellow powder with soft texture for various industrial applications.',
    sodaAshDesc: 'Dense and light soda ash for glass industry, detergent production, and chemical applications.',
    waterTreatmentDesc: 'Manganese dioxide media filter for water purification and treatment systems.',
    fluorsparDesc: 'Fluxing agent for metallurgical slags used in steel and ferro alloy manufacturing.',

    // Product Features
    concentrate75Micron: 'Concentrate (75 micron)',
    powder05mm: 'Powder (0-5 mm)',
    lumps312: 'Lumps (3-12, 10-50, 50-100 mm)',
    ebtSand: 'EBT Sand',
    foundrySand: 'Foundry Sand',
    blastingSand: 'Blasting Sand',
    refractorySpray: 'Refractory Spray Sand',
    mn3o4: 'Mn3O4',
    ferroManganese: 'Ferro Manganese',
    manganeseOxide: 'Manganese Oxide',
    powderForms: 'Powder Forms',
    foundryGrade: 'Foundry Grade',
    betterSurfaceFinish: 'Better Surface Finish',
    reducedDefects: 'Reduced Casting Defects',
    highPurity: 'High Purity',
    powderForm: 'Powder Form',
    industrialGrade: 'Industrial Grade',
    steelManufacturing: 'Steel Manufacturing',
    stainlessSteel: 'Stainless Steel',
    ferroAlloys: 'Ferro Alloys',
    baseMetals: 'Base Metals',

    // Products Page
    ourProductsPage: 'Our Products',
    productsPageDesc: 'Comprehensive range of premium industrial minerals for steel mills, foundries, and chemical industries worldwide.',
    allProducts: 'All Products',
    metalsAlloys: 'Metals & Alloys',
    foundryMaterials: 'Foundry Materials',
    chemicals: 'Chemicals',
    needCustomSolution: 'Need a Custom Solution?',
    customSolutionDesc: 'Contact our team for customized mineral solutions tailored to your specific requirements.',
    getCustomQuote: 'Get Custom Quote',
    availableSizes: 'Available Sizes',
    
    // Applications
    steelMills: 'Steel Mills',
    chemicalIndustry: 'Chemical Industry',
    cementProduction: 'Cement Production',
    foundries: 'Foundries',
    refractory: 'Refractory',
    blasting: 'Blasting',
    batteryProduction: 'Battery Production',
    steelCasting: 'Steel Casting',
    investmentCasting: 'Investment Casting',
    fertilizer: 'Fertilizer',
    rubberIndustry: 'Rubber Industry',
    glassIndustry: 'Glass Industry',
    detergentProduction: 'Detergent Production',
    paperIndustry: 'Paper Industry',
    waterTreatmentApp: 'Water Treatment',
    filtrationSystems: 'Filtration Systems',
    purification: 'Purification',
    aluminumIndustry: 'Aluminum Industry',

    // Company Page
    aboutNovaTitle: 'About Nova Minerals',
    companyHeroDesc: 'Leading supplier of premium industrial minerals with complete supply chain management from Turkish mines to global markets.',
    yearsExperience: 'Years Experience',
    member: 'IMMBI Member',
    ourMission: 'Our Mission',
    missionText: 'To provide high-quality industrial minerals and exceptional service to customers worldwide, while maintaining the highest standards of safety, environmental responsibility, and ethical business practices.',
    ourVision: 'Our Vision',
    visionText: 'To be the most trusted and reliable partner for industrial mineral solutions globally, recognized for our quality, innovation, and customer-centric approach.',
    ourStory: 'Our Story',
    storyDesc: 'Nova Minerals has established itself as Turkey\'s leading exporter of industrial minerals, with a comprehensive approach to supply chain management.',
    completeSupplyChainMgmt: 'Complete Supply Chain Management',
    supplyChainDesc1: 'From mining operations to final delivery, we control every step of the process. Our integrated approach ensures consistent quality, reliable supply, and competitive pricing for our customers worldwide.',
    supplyChainDesc2: 'With strategic partnerships and our own mining operations, we maintain full control over production schedules, quality standards, and logistics coordination.',
    uniqueMarketPosition: 'Unique Market Position',
    uniquePositionDesc: 'As Turkey\'s only producer of Iron Pyrite lumps and a leading supplier of premium Olivine, we hold unique positions in specialized mineral markets.',
    keyCapabilities: 'Key Capabilities',
    miningOperations: 'Mining Operations',
    miningOperationsDesc: 'Direct control over extraction and processing',
    qualityControl: 'Quality Control',
    qualityControlDesc: 'Rigorous testing and certification processes',
    globalLogistics: 'Global Logistics',
    globalLogisticsDesc: 'Efficient worldwide shipping and distribution',
    customerSupport: 'Customer Support',
    customerSupportDesc: 'Dedicated account management and technical support',
    ourValues: 'Our Values',
    valuesDesc: 'Our core values guide every decision we make and every relationship we build.',
    qualityExcellence: 'Quality Excellence',
    qualityExcellenceDesc: 'Uncompromising commitment to product quality and continuous improvement in all processes.',
    transparency: 'Transparency',
    transparencyDesc: 'Open, honest communication with customers, suppliers, and stakeholders at all times.',
    reliability: 'Reliability',
    reliabilityDesc: 'Dependable delivery performance and consistent product quality that customers can count on.',
    innovation: 'Innovation',
    innovationDesc: 'Continuous investment in technology, processes, and solutions to better serve our customers.',
    whyChooseNovaTitle: 'Why Choose Nova Minerals?',
    whyChooseDesc: 'Our unique combination of market position, global reach, and customer focus sets us apart.',
    marketLeadership: 'Market Leadership',
    marketLeadershipDesc: 'Unique positions in specialized mineral markets with proven track record of excellence.',
    exclusiveProduction: 'Turkey\'s only Iron Pyrite lumps producer',
    premiumOlivine: 'Premium Olivine from Turkish mines',
    immbiMembership: 'IMMBI membership and industry recognition',
    globalReach: 'Global Reach',
    globalReachDesc: 'Serving customers in over 50 countries with efficient logistics and reliable supply chains.',
    worldwideDistribution: 'Worldwide distribution network',
    strategicPortLocation: 'Strategic port location advantages',
    efficientLogistics: 'Efficient logistics and shipping',
    customerPartnership: 'Customer Partnership',
    customerPartnershipDesc: 'Building long-term relationships through transparency, reliability, and exceptional service.',
    openDialogue: 'Open dialogue and communication',
    dedicatedAccountMgmt: 'Dedicated account management',
    contractualCompliance: 'Contractual compliance and reliability',
    certificationsTitle: 'Certifications & Memberships',
    certificationsDesc: 'Our commitment to quality and industry standards is reflected in our certifications.',
    istanbulMineralsExporters: 'Istanbul Minerals & Metals Exporters Association',
    immbiDesc: 'Proud member of IMMBI, Turkey\'s leading minerals and metals exporters association, ensuring adherence to highest industry standards.',
    qualityAssuranceTitle: 'Quality Assurance',
    qualityAssuranceFullDesc: 'Comprehensive quality management systems ensuring consistent product quality and customer satisfaction through rigorous testing and certification processes.',
    partnerWithNova: 'Partner with Nova Minerals',
    partnerDesc: 'Experience the difference of working with Turkey\'s leading industrial minerals supplier.',
    contactUs: 'Contact Us',
    viewProducts: 'View Products',

    // Contact Page
    contactHeroDesc: 'Get in touch with our team for quotes, product information, or any questions about our premium industrial minerals.',
    fullName: 'Full Name',
    fullNamePlaceholder: 'Your full name',
    emailAddress: 'Email Address',
    emailPlaceholder: 'your@email.com',
    companyName: 'Company Name',
    companyNamePlaceholder: 'Your company name',
    phoneNumber: 'Phone Number',
    phonePlaceholder: '+90 xxx xxx xxxx',
    productInterest: 'Product Interest',
    selectProduct: 'Select a product',
    multipleProducts: 'Multiple Products',
    other: 'Other',
    expectedQuantity: 'Expected Quantity',
    quantityPlaceholder: 'e.g., 100 tons/month',
    message: 'Message',
    messagePlaceholder: 'Please provide details about your requirements, specifications, delivery location, etc.',
    sendQuoteRequest: 'Send Quote Request',
    formSubmitted: 'Form submitted! We will contact you soon.',
    companyAddress: 'Zülfü Tiğrel Cad. Eti Maden Sitesi\nNo:35/8 Çankaya/Ankara, Turkey',
    website: 'Website',
    businessHours: 'Business Hours',
    mondayFriday: 'Monday - Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    closed: 'Closed',
    supportTitle: '24/7 Support',
    supportDesc: 'For urgent inquiries, please call our emergency line or send an email. We respond to all messages within 24 hours.',
    quickContact: 'Quick Contact',
    callNow: 'Call Now',
    sendEmail: 'Send Email',
    whatsapp: 'WhatsApp',
    chatInstantly: 'Chat with us instantly',
    ourLocation: 'Our Location',
    visitUs: 'Visit us at our headquarters in Ankara, Turkey',
    interactiveMap: 'Interactive Map',
    googleMapsIntegration: 'Google Maps integration can be added here',

    // =================== EKSİK OLAN ÇEVİRİLER ===================
    
    // Product Detail Pages - Common
    productOverview: 'Product Overview',
    keyFeatures: 'Key Features',
    technicalProperties: 'Technical Properties',
    originSupply: 'Origin & Supply',
    origin: 'Origin',
    supplyChain: 'Supply Chain',
    relatedProducts: 'Related Products',
    primaryApplications: 'Primary Applications',
    chemicalFormula: 'Chemical Formula',
    availableGrades: 'Available Grades',
    availableForms: 'Available Forms',
    availableTypes: 'Available Types',
    productTypes: 'Product Types',
    keyProperties: 'Key Properties',
    keyBenefits: 'Key Benefits',
    availableProducts: 'Available Products',
    areasOfUsage: 'Areas of Usage',
    technicalSpecifications: 'Technical Specifications',

    // Iron Pyrite Specific
    ironPyriteOverview: 'We are the only producer of Iron Pyrite Lumps in Turkey. Our mine is located near the Gemlik Port which gives us an advantage for transportation. We offer Iron Pyrite Concentrate as well.',
    ironPyriteConcentrate: 'Iron Pyrite Concentrate',
    powder: 'Powder',
    lumps: 'Lumps',
    packingOptions: 'Packing Options',
    bulk: 'Bulk',
    bags25kg: '25kg Bags',
    bigBags1Mt: '1Mt Big Bags',
    component: 'Component',
    concentrate: 'Concentrate',
    lump: 'Lump',
    sulfuricAcidProduction: 'Sulfuric Acid Production',
    whyChooseOurIronPyrite: 'Why Choose Our Iron Pyrite?',
    onlyProducerInTurkey: 'Only Producer in Turkey',
    uniqueMarketPositionReliableSupply: 'Unique market position with reliable supply chain and quality assurance.',
    nearGemlikPortOptimizedLogistics: 'Near Gemlik Port for optimized logistics and cost-effective shipping worldwide.',
    consistentQualityReliableSpecs: 'Consistent quality with reliable specifications meeting international standards.',
    premiumQuality: 'Premium Quality',
    multipleSizes: 'Multiple Sizes',

    // Olivine Specific
    olivineOverview: 'We supply one of the best quality Olivine for different applications including foundry, blasting, refractory, and slag conditioning.',
    bestQuality: 'Best Quality',
    multipleApplications: 'Multiple Applications',
    slagSand: 'Slag Sand',
    highMeltingPoint: 'High Melting Point',
    hardness: 'Hardness',
    density: 'Density',
    chemicalStability: 'Chemical Stability',
    excellent: 'Excellent',
    refractoryIndustry: 'Refractory Industry',
    blastingApplications: 'Blasting Applications',
    olivineFoundryApp: 'Excellent thermal properties for foundry moulding and core making applications.',
    olivineRefractoryApp: 'High melting point and chemical stability for refractory spray applications.',
    olivineSteelApp: 'Superior slag conditioning properties for steel mill applications.',
    olivineBlastingApp: 'Environmentally friendly abrasive for surface preparation and cleaning.',
    whyChooseOurOlivine: 'Why Choose Our Olivine?',
    superiorQuality: 'Superior Quality',
    olivineSuperiorDesc: 'Highest quality olivine sourced from Turkish mines with consistent specifications.',
    versatileApplications: 'Versatile Applications',
    olivineVersatileDesc: 'Suitable for foundry, refractory, blasting, and steel industry applications.',
    reliableSupply: 'Reliable Supply',
    olivineReliableDesc: 'Consistent supply chain with strategic location advantages for worldwide delivery.',

    // Manganese Specific
    manganeseOverview: 'Various manganese compounds available for metallurgical, chemical, and battery production applications.',
    multipleForms: 'Multiple Forms',
    ferroAlloyProduction: 'Ferro Alloy Production',
    chemicalComposition: 'Chemical Composition',
    manganeseChemicalDesc: 'High-grade manganese compounds with consistent chemical composition for various industrial applications.',
    particleSize: 'Particle Size',
    manganeseParticleSizeDesc: 'Available in various particle sizes to meet specific application requirements.',
    qualityStandards: 'Quality Standards',
    manganeseQualityDesc: 'Adhering to international quality standards with certified specifications.',
    whyChooseOurManganese: 'Why Choose Our Manganese?',
    consistentQuality: 'Consistent Quality',
    manganeseConsistentDesc: 'Reliable quality standards with consistent chemical composition and specifications.',
    manganeseMultipleDesc: 'Available in various forms including Mn3O4, ferro manganese, and oxide compounds.',
    manganeseReliableDesc: 'Dependable supply chain with strategic sourcing and quality assurance programs.',

    // Chromite Sand Specific
    superiorFinish: 'Superior Finish',
    chromiteSandOverview: 'High-quality chromite sand for foundry applications providing excellent surface finish and reduced casting defects.',
    reducedCastingDefects: 'Reduced Casting Defects',
    highThermalConductivity: 'High Thermal Conductivity',
    foundryMoldingSand: 'Foundry Moulding Sand',
    coreMaking: 'Core Making',
    pigmentProduction: 'Pigment Production',
    meltingPoint: 'Melting Point',
    thermalExpansion: 'Thermal Expansion',
    low: 'Low',
    chromiteSandOrigin: 'Sourced from high-quality chromite deposits with consistent mineral composition.',
    chromiteSandSupply: 'Strategic supply chain management ensuring reliable delivery worldwide.',
    whyChooseOurChromiteSand: 'Why Choose Our Chromite Sand?',
    chromiteSandQualityDesc: 'Superior quality chromite sand with excellent thermal properties for foundry applications.',
    betterCastingResults: 'Better Casting Results',
    chromiteSandResultsDesc: 'Enhanced surface finish and reduced defects in casting applications.',
    directSupply: 'Direct Supply',
    chromiteSandSupplyDesc: 'Direct supply from mines ensuring cost-effective pricing and reliable quality.',

    // Fluorspar Specific
    fluxingAgent: 'Fluxing Agent',
    southAfricanOrigin: 'South African Origin',
    fluorsparOverview: 'Premium quality fluorspar from South African mines, serving as an effective fluxing agent for metallurgical applications.',
    acidGrade: 'Acid Grade',
    metallurgicalGrade: 'Metallurgical Grade',
    ceramicGrade: 'Ceramic Grade',
    calciumFluoride: 'Calcium Fluoride',
    republicOfSouthAfricaOrigin: 'Republic of South Africa Origin',
    stainlessSteelProduction: 'Stainless Steel Production',
    fluorsparSteelApp: 'Effective fluxing agent for steel production reducing melting temperature.',
    fluorsparStainlessApp: 'Essential for stainless steel production improving slag fluidity.',
    fluorsparFerroApp: 'Critical component in ferro alloy production for improved efficiency.',
    fluorsparBaseMetalsApp: 'Used in base metal refining processes for better metal recovery.',
    fluorsparAluminumApp: 'Essential for aluminum smelting reducing energy consumption.',
    caf2Content: 'CaF2 Content',
    whyChooseOurFluorspar: 'Why Choose Our Fluorspar?',
    southAfricanQuality: 'South African Quality',
    fluorsparQualityDesc: 'Premium quality fluorspar from South African mines with high CaF2 content.',
    multipleGrades: 'Multiple Grades',
    fluorsparGradesDesc: 'Available in acid, metallurgical, and ceramic grades for various applications.',
    consistentSupply: 'Consistent Supply',
    fluorsparSupplyDesc: 'Reliable supply chain from South African sources ensuring consistent quality.',

    // Soda Ash Specific
    turkishOrigin: 'Turkish Origin',
    sodaAshOverview: 'High-quality soda ash from Turkish sources for glass, chemical, and detergent industry applications.',
    denseSodaAsh: 'Dense Soda Ash',
    lightSodaAsh: 'Light Soda Ash',
    sodiumCarbonate: 'Sodium Carbonate',
    clearColorlessAqueousSolution: 'Clear, colorless aqueous solution',
    soapDetergentIndustry: 'Soap & Detergent Industry',
    paperProduction: 'Paper Production',
    sodaAshGlassApp: 'Essential raw material for glass manufacturing reducing melting temperature.',
    sodaAshChemicalApp: 'Key component in chemical production for various industrial processes.',
    sodaAshSoapApp: 'Critical ingredient in soap and detergent manufacturing for alkalinity.',
    sodaAshPaperApp: 'Used in paper production for pulping and bleaching processes.',
    sodaAshWaterApp: 'Water treatment applications for pH adjustment and softening.',
    sodiumBicarbonate: 'Sodium Bicarbonate',
    sodiumBicarbonateDesc: 'High-quality sodium bicarbonate available in food, feed, and technical grades.',
    foodGrade: 'Food Grade',
    feedGrade: 'Feed Grade',
    technicalGrade: 'Technical Grade',
    whyChooseOurSodaAsh: 'Why Choose Our Soda Ash?',
    sodaAshOriginDesc: 'High-quality soda ash from reliable Turkish sources with consistent specifications.',
    sodaAshAppsDesc: 'Suitable for glass, chemical, detergent, and paper industry applications.',
    sodaAshQualityDesc: 'Consistent quality with reliable specifications meeting international standards.',

    // Sulphur Specific
    sulphurOverview: 'High-purity sulphur in various forms for chemical, fertilizer, and rubber industry applications.',
    granular: 'Granular',
    appearance: 'Appearance',
    brightYellow: 'Bright Yellow',
    texture: 'Texture',
    softPowder: 'Soft Powder',
    purity: 'Purity',
    highGrade: 'High Grade',
    pharmaceutical: 'Pharmaceutical',
    sulphurChemicalApp: 'Essential for sulfuric acid production and various chemical processes.',
    sulphurFertilizerApp: 'Key component in fertilizer production for soil acidification.',
    sulphurRubberApp: 'Critical for rubber vulcanization improving elasticity and durability.',
    sulphurPharmaApp: 'Pharmaceutical applications in topical treatments and medications.',
    sulphurContent: 'Sulphur Content',
    moisture: 'Moisture',
    ashContent: 'Ash Content',
    various: 'Various',
    whyChooseOurSulphur: 'Why Choose Our Sulphur?',
    sulphurHighPurityDesc: 'High-purity sulphur with 99.5% minimum content for industrial applications.',
    sulphurConsistentDesc: 'Consistent quality with reliable specifications and certified analysis.',
    sulphurMultipleFormsDesc: 'Available in powder, granular, and lump forms for various applications.',

    // Water Treatment Specific
    mediaFilter: 'Media Filter',
    highPerformance: 'High Performance',
    waterTreatmentOverview: 'Manganese dioxide media filter for effective water purification and treatment applications.',
    manganeseDioxide: 'Manganese Dioxide',
    variousGrades: 'Various Grades',
    ironManganeseRemoval: 'Iron & Manganese Removal',
    hydrogenSulfideReduction: 'Hydrogen Sulfide Reduction',
    tasteOdorImprovement: 'Taste & Odor Improvement',
    longServiceLife: 'Long Service Life',
    lowMaintenance: 'Low Maintenance',
    municipalWaterTreatment: 'Municipal Water Treatment',
    industrialWaterProcessing: 'Industrial Water Processing',
    wellWaterTreatment: 'Well Water Treatment',
    waterMunicipalApp: 'Effective for municipal water treatment systems removing iron and manganese.',
    waterIndustrialApp: 'Industrial water processing applications for quality improvement.',
    waterWellApp: 'Well water treatment for residential and commercial applications.',
    waterFiltrationApp: 'Advanced filtration systems for comprehensive water treatment.',
    phRange: 'pH Range',
    porosity: 'Porosity',
    high: 'High',
    whyChooseOurWaterTreatment: 'Why Choose Our Water Treatment Products?',
    effectiveFiltration: 'Effective Filtration',
    waterEffectiveDesc: 'Highly effective filtration media for comprehensive water treatment.',
    costEffective: 'Cost Effective',
    waterCostDesc: 'Cost-effective solution with long service life and low maintenance requirements.',
    reliablePerformance: 'Reliable Performance',
    waterReliableDesc: 'Consistent performance with reliable contaminant removal capabilities.',

    // Additional missing keys
    unique: 'Unique',
    ironPyriteProducer: 'Iron Pyrite Producer',
    steelIndustry: 'Steel Industry',
    steelProduction: 'Steel Production'
  },
  tr: {
    // Header
    home: 'Ana Sayfa',
    company: 'Hakkımızda',
    products: 'Ürünler',
    contact: 'İletişim',
    getQuote: 'Teklif Al',
    
    // Hero Section
    heroSubtitle: "Türkiye'nin Tek Toprak Demir Piriti Üreticisi",
    heroTitle1: 'Premium Endüstriyel',
    heroTitle2: 'Mineraller',
    heroDescription: 'Dünya çapında çelik fabrikaları ve dökümhaneler için yüksek kaliteli demir piriti, olivin, manganez ve özel mineraller ile hammadde endüstrilerine hizmet veriyoruz.',
    exploreProducts: 'Ürünleri Keşfet',
    
    // Stats
    productLines: 'Ürün Hattı',
    countriesServed: 'Hizmet Verilen Ülke',
    support: 'Destek',
    
    // Features
    globalSupplyChain: 'Küresel Tedarik Zinciri',
    globalSupplyDesc: 'Madenlerden dünya çapında tüketicilere kadar tam tedarik zinciri yönetimi',
    qualityAssured: 'Kalite Güvencesi',
    qualityAssuredDesc: 'İMMİB üyesi ile sertifikalı kalite standartları',
    strategicLocation: 'Stratejik Konum',
    strategicLocationDesc: 'Optimize edilmiş nakliye için Gemlik Limanı yakınında',
    
    // Products Section
    ourProducts: 'Premium Ürünlerimiz',
    productsDescription: 'Dünya çapında çelik fabrikaları ve dökümhanelerin zorlu gereksinimlerini karşılamak için kaynaklanan ve işlenen yüksek kaliteli endüstriyel mineraller.',
    viewAllProducts: 'Tüm Ürünleri Görüntüle',
    learnMore: 'Daha Fazla Bilgi',
    
    // Company Section
    aboutNova: 'Nova Minerals Hakkında',
    companyDescription1: 'Nova Minerals, çelik fabrikaları ve dökümhanelerin gereksinimlerini karşılayarak endüstriyel mineraller ve malzemelerin temini ve pazarlamasına öncelikli olarak odaklanmaktadır. Kapsamlı yaklaşımımız, maden işletmelerimizden başlayarak küresel tüketici pazarına kadar uzanan tüm tedarik zincirini kapsar.',
    companyDescription2: 'Etkileşimlerimizin temel taşları açık diyalog ve şeffaflıktır, hem kaynaklarımız hem de müşterilerimizle bağlantılarımızın temelini oluşturur. Türkiye\'nin tek Toprak Demir Piriti üreticisi olmaktan ve İstanbul Mineral İhracatçıları Birliği (İMMBİ) üyesi olmaktan gurur duyuyoruz.',
    learnMoreAbout: 'Hakkımızda Daha Fazla Bilgi',
    whyChooseNova: 'Neden Nova Minerals?',
    completeSupplyChain: 'Tam Tedarik Zinciri',
    completeSupplyDesc: 'Maden işletmelerinden küresel teslimat',
    qualityAssurance: 'Kalite Güvencesi',
    qualityAssuranceDesc: 'Sertifikalı standartlar ve tutarlı kalite',
    strategicLocationFull: 'Stratejik Konum',
    strategicLocationFullDesc: 'Optimize edilmiş lojistik için Gemlik Limanı yakınında',
    dedicatedSupport: 'Özel Destek',
    dedicatedSupportDesc: 'Tüm ihtiyaçlar için tek iletişim noktası',
    
    // Footer
    footerDescription: 'Dünya çapında çelik fabrikaları ve dökümhaneler için premium endüstriyel minerallerin önde gelen tedarikçisi. Türkiye\'nin tek Demir Piriti Toprak üreticisi.',
    address: 'Adres',
    phone: 'Telefon',
    email: 'E-posta',
    quickLinks: 'Hızlı Linkler',
    footerCopyright: 'Nova Minerals. Tüm hakları saklıdır. | İMMBİ Üyesi',
    
    // Common
    available: 'Mevcut',
    specifications: 'Özellikler',
    applications: 'Uygulamalar',
    contactInfo: 'İletişim Bilgileri',
    
    // Breadcrumb
    breadcrumbHome: 'Ana Sayfa',
    breadcrumbProducts: 'Ürünler',
    breadcrumbCompany: 'Hakkımızda',
    breadcrumbContact: 'İletişim',

    // Product Names
    ironPyrite: 'Demir Piriti',
    olivine: 'Olivin',
    manganese: 'Manganez',
    chromiteSand: 'Kromit Kumu',
    sulphur: 'Kükürt',
    sodaAsh: 'Soda Külü',
    waterTreatment: 'Su Arıtma',
    fluorspar: 'Florit',

    // Product Descriptions
    ironPyriteDesc: "Türkiye'nin tek toprak demir piriti üreticisi. 75 mikrondan 100mm topraklara kadar çoklu boyut seçenekleri.",
    olivineDesc: 'Döküm, kumlama, refraktör ve cüruf uygulamaları için premium kalite olivin.',
    manganeseDesc: 'Metalurji ve kimya uygulamaları için çeşitli manganez bileşikleri.',
    chromiteSandDesc: 'Mükemmel yüzey kalitesi ile döküm uygulamaları için yüksek kaliteli kromit kumu.',
    sulphurDesc: 'Çeşitli endüstriyel uygulamalar için yumuşak dokulu parlak sarı toz.',
    sodaAshDesc: 'Cam endüstrisi, deterjan üretimi ve kimyasal uygulamalar için yoğun ve hafif soda külü.',
    waterTreatmentDesc: 'Su arıtma ve arıtma sistemleri için manganez dioksit medya filtresi.',
    fluorsparDesc: 'Çelik ve ferro alaşım üretiminde kullanılan metalurjik cüruflar için akıştırıcı madde.',

    // Product Features
    concentrate75Micron: 'Konsantre (75 mikron)',
    powder05mm: 'Toz (0-5 mm)',
    lumps312: 'Topraklar (3-12, 10-50, 50-100 mm)',
    ebtSand: 'EBT Kumu',
    foundrySand: 'Döküm Kumu',
    blastingSand: 'Kumlama Kumu',
    refractorySpray: 'Refraktör Sprey Kumu',
    mn3o4: 'Mn3O4',
    ferroManganese: 'Ferro Manganez',
    manganeseOxide: 'Manganez Oksit',
    powderForms: 'Toz Formları',
    foundryGrade: 'Döküm Kalitesi',
    betterSurfaceFinish: 'Daha İyi Yüzey Kalitesi',
    reducedDefects: 'Azaltılmış Döküm Hataları',
    highPurity: 'Yüksek Saflık',
    powderForm: 'Toz Formu',
    industrialGrade: 'Endüstriyel Kalite',
    steelManufacturing: 'Çelik Üretimi',
    stainlessSteel: 'Paslanmaz Çelik',
    ferroAlloys: 'Ferro Alaşımlar',
    baseMetals: 'Baz Metaller',

    // Products Page
    ourProductsPage: 'Ürünlerimiz',
    productsPageDesc: 'Dünya çapında çelik fabrikaları, dökümhaneler ve kimya endüstrileri için kapsamlı premium endüstriyel mineraller yelpazesi.',
    allProducts: 'Tüm Ürünler',
    metalsAlloys: 'Metaller ve Alaşımlar',
    foundryMaterials: 'Döküm Malzemeleri',
    chemicals: 'Kimyasallar',
    needCustomSolution: 'Özel Çözüme İhtiyacınız Var mı?',
    customSolutionDesc: 'Özel gereksinimlerinize göre özelleştirilmiş mineral çözümleri için ekibimizle iletişime geçin.',
    getCustomQuote: 'Özel Teklif Al',
    availableSizes: 'Mevcut Boyutlar',
    
    // Applications
    steelMills: 'Çelik Fabrikaları',
    chemicalIndustry: 'Kimya Endüstrisi',
    cementProduction: 'Çimento Üretimi',
    foundries: 'Dökümhaneler',
    refractory: 'Refraktör',
    blasting: 'Kumlama',
    batteryProduction: 'Batarya Üretimi',
    steelCasting: 'Çelik Döküm',
    investmentCasting: 'Hassas Döküm',
    fertilizer: 'Gübre',
    rubberIndustry: 'Kauçuk Endüstrisi',
    glassIndustry: 'Cam Endüstrisi',
    detergentProduction: 'Deterjan Üretimi',
    paperIndustry: 'Kağıt Endüstrisi',
    waterTreatmentApp: 'Su Arıtma',
    filtrationSystems: 'Filtrasyon Sistemleri',
    purification: 'Arıtma',
    aluminumIndustry: 'Alüminyum Endüstrisi',

    // Company Page
    aboutNovaTitle: 'Nova Minerals Hakkında',
    companyHeroDesc: 'Türk madenlerinden küresel pazarlara tam tedarik zinciri yönetimi ile premium endüstriyel minerallerin önde gelen tedarikçisi.',
    yearsExperience: 'Yıllık Deneyim',
    member: 'İMMİB Üyesi',
    ourMission: 'Misyonumuz',
    missionText: 'Dünya çapındaki müşterilere yüksek kaliteli endüstriyel mineraller ve olağanüstü hizmet sağlamak, aynı zamanda en yüksek güvenlik, çevresel sorumluluk ve etik iş uygulamaları standartlarını korumak.',
    ourVision: 'Vizyonumuz',
    visionText: 'Kalite, inovasyon ve müşteri odaklı yaklaşımımızla tanınan, endüstriyel mineral çözümleri için küresel olarak en güvenilir ve güvenilir ortak olmak.',
    ourStory: 'Hikayemiz',
    storyDesc: 'Nova Minerals, tedarik zinciri yönetimine kapsamlı bir yaklaşımla Türkiye\'nin önde gelen endüstriyel mineral ihracatçısı olarak kendini kurmuştur.',
    completeSupplyChainMgmt: 'Tam Tedarik Zinciri Yönetimi',
    supplyChainDesc1: 'Maden işletmelerinden nihai teslimat aşamasına kadar sürecin her adımını kontrol ediyoruz. Entegre yaklaşımımız, dünya çapındaki müşterilerimiz için tutarlı kalite, güvenilir tedarik ve rekabetçi fiyatlandırma sağlar.',
    supplyChainDesc2: 'Stratejik ortaklıklar ve kendi maden işletmelerimizle, üretim programları, kalite standartları ve lojistik koordinasyonu üzerinde tam kontrol sağlıyoruz.',
    uniqueMarketPosition: 'Benzersiz Pazar Konumu',
    uniquePositionDesc: 'Türkiye\'nin tek Demir Pirit yumru üreticisi ve premium Olivin\'in önde gelen tedarikçisi olarak, özel mineral pazarlarında benzersiz konumlara sahibiz.',
    keyCapabilities: 'Ana Yetenekler',
    miningOperations: 'Maden İşletmeleri',
    miningOperationsDesc: 'Çıkarma ve işleme üzerinde doğrudan kontrol',
    qualityControl: 'Kalite Kontrol',
    qualityControlDesc: 'Titiz test ve sertifikasyon süreçleri',
    globalLogistics: 'Global Lojistik',
    globalLogisticsDesc: 'Verimli dünya çapında nakliye ve dağıtım',
    customerSupport: 'Müşteri Desteği',
    customerSupportDesc: 'Özel hesap yönetimi ve teknik destek',
    ourValues: 'Değerlerimiz',
    valuesDesc: 'Temel değerlerimiz, verdiğimiz her kararı ve kurduğumuz her ilişkiyi yönlendirir.',
    qualityExcellence: 'Kalite Mükemmelliği',
    qualityExcellenceDesc: 'Ürün kalitesine taviz vermeyen bağlılık ve tüm süreçlerde sürekli iyileştirme.',
    transparency: 'Şeffaflık',
    transparencyDesc: 'Müşteriler, tedarikçiler ve paydaşlarla her zaman açık, dürüst iletişim.',
    reliability: 'Güvenilirlik',
    reliabilityDesc: 'Müşterilerin güvenebileceği bağımlı teslimat performansı ve tutarlı ürün kalitesi.',
    innovation: 'İnovasyon',
    innovationDesc: 'Müşterilerimize daha iyi hizmet vermek için teknoloji, süreçler ve çözümlere sürekli yatırım.',
    whyChooseNovaTitle: 'Neden Nova Minerals?',
    whyChooseDesc: 'Pazar konumumuz, küresel erişimimiz ve müşteri odaklılığımızın benzersiz kombinasyonu bizi farklı kılar.',
    marketLeadership: 'Pazar Liderliği',
    marketLeadershipDesc: 'Kanıtlanmış mükemmellik sicili ile özel mineral pazarlarında benzersiz konumlar.',
    exclusiveProduction: 'Türkiye\'nin tek Demir Pirit yumru üreticisi',
    premiumOlivine: 'Türk madenlerinden premium Olivin',
    immbiMembership: 'İMMİB üyeliği ve sektör tanınırlığı',
    globalReach: 'Küresel Erişim',
    globalReachDesc: 'Verimli lojistik ve güvenilir tedarik zincirleri ile 50\'den fazla ülkede müşterilere hizmet veriyoruz.',
    worldwideDistribution: 'Dünya çapında dağıtım ağı',
    strategicPortLocation: 'Stratejik liman konumu avantajları',
    efficientLogistics: 'Verimli lojistik ve nakliye',
    customerPartnership: 'Müşteri Ortaklığı',
    customerPartnershipDesc: 'Şeffaflık, güvenilirlik ve olağanüstü hizmet ile uzun vadeli ilişkiler kuruyoruz.',
    openDialogue: 'Açık diyalog ve iletişim',
    dedicatedAccountMgmt: 'Özel hesap yönetimi',
    contractualCompliance: 'Sözleşme uyumluluğu ve güvenilirlik',
    certificationsTitle: 'Sertifikalar ve Üyelikler',
    certificationsDesc: 'Kalite ve sektör standartlarına bağlılığımız sertifikalarımızda yansıyor.',
    istanbulMineralsExporters: 'İstanbul Maden ve Metaller İhracatçıları Birliği',
    immbiDesc: 'Türkiye\'nin önde gelen maden ve metal ihracatçıları birliği İMMİB\'in gururlu üyesi olarak, en yüksek sektör standartlarına uygunluğu sağlıyoruz.',
    qualityAssuranceTitle: 'Kalite Güvencesi',
    qualityAssuranceFullDesc: 'Titiz test ve sertifikasyon süreçleri ile tutarlı ürün kalitesi ve müşteri memnuniyetini sağlayan kapsamlı kalite yönetim sistemleri.',
    partnerWithNova: 'Nova Minerals ile Ortaklık',
    partnerDesc: 'Türkiye\'nin önde gelen endüstriyel mineral tedarikçisi ile çalışmanın farkını yaşayın.',
    contactUs: 'İletişime Geçin',
    viewProducts: 'Ürünleri Görüntüle',

    // Contact Page
    contactHeroDesc: 'Premium endüstriyel minerallerimiz hakkında teklifler, ürün bilgileri veya herhangi bir sorunuz için ekibimizle iletişime geçin.',
    fullName: 'Ad Soyad',
    fullNamePlaceholder: 'Adınız ve soyadınız',
    emailAddress: 'E-posta Adresi',
    emailPlaceholder: 'sizin@email.com',
    companyName: 'Şirket Adı',
    companyNamePlaceholder: 'Şirket adınız',
    phoneNumber: 'Telefon Numarası',
    phonePlaceholder: '+90 xxx xxx xxxx',
    productInterest: 'Ürün İlgisi',
    selectProduct: 'Bir ürün seçin',
    multipleProducts: 'Birden Fazla Ürün',
    other: 'Diğer',
    expectedQuantity: 'Beklenen Miktar',
    quantityPlaceholder: 'örn., 100 ton/ay',
    message: 'Mesaj',
    messagePlaceholder: 'Lütfen gereksinimleriniz, özellikler, teslimat yeri vb. hakkında detay verin.',
    sendQuoteRequest: 'Teklif Talebi Gönder',
    formSubmitted: 'Form gönderildi! En kısa sürede sizinle iletişime geçeceğiz.',
    companyAddress: 'Zülfü Tiğrel Cad. Eti Maden Sitesi\nNo:35/8 Çankaya/Ankara, Türkiye',
    website: 'Web Sitesi',
    businessHours: 'Çalışma Saatleri',
    mondayFriday: 'Pazartesi - Cuma',
    saturday: 'Cumartesi',
    sunday: 'Pazar',
    closed: 'Kapalı',
    supportTitle: '7/24 Destek',
    supportDesc: 'Acil sorularınız için lütfen acil durum hattımızı arayın veya e-posta gönderin. Tüm mesajlara 24 saat içinde yanıt veriyoruz.',
    quickContact: 'Hızlı İletişim',
    callNow: 'Şimdi Ara',
    sendEmail: 'E-posta Gönder',
    whatsapp: 'WhatsApp',
    chatInstantly: 'Anında sohbet edin',
    ourLocation: 'Konumumuz',
    visitUs: 'Ankara, Türkiye\'deki merkezimizi ziyaret edin',
    interactiveMap: 'Etkileşimli Harita',
    googleMapsIntegration: 'Google Haritalar entegrasyonu burada eklenebilir',

    // =================== EKSİK OLAN ÇEVİRİLER - TÜRKÇE ===================
    
    // Product Detail Pages - Common
    productOverview: 'Ürün Genel Bakışı',
    keyFeatures: 'Ana Özellikler',
    technicalProperties: 'Teknik Özellikler',
    originSupply: 'Köken ve Tedarik',
    origin: 'Köken',
    supplyChain: 'Tedarik Zinciri',
    relatedProducts: 'İlgili Ürünler',
    primaryApplications: 'Birincil Uygulamalar',
    chemicalFormula: 'Kimyasal Formül',
    availableGrades: 'Mevcut Kaliteler',
    availableForms: 'Mevcut Formlar',
    availableTypes: 'Mevcut Türler',
    productTypes: 'Ürün Türleri',
    keyProperties: 'Ana Özellikler',
    keyBenefits: 'Ana Faydalar',
    availableProducts: 'Mevcut Ürünler',
    areasOfUsage: 'Kullanım Alanları',
    technicalSpecifications: 'Teknik Özellikler',

    // Iron Pyrite Specific - Turkish
    ironPyriteOverview: 'Türkiye\'de Demir Pirit Yumrularının tek üreticisiyiz. Madenimiz Gemlik Limanı yakınında yer alır ve bu da nakliye konusunda avantaj sağlar. Demir Pirit Konsantresi de sunmaktayız.',
    ironPyriteConcentrate: 'Demir Pirit Konsantresi',
    powder: 'Toz',
    lumps: 'Yumrular',
    packingOptions: 'Ambalaj Seçenekleri',
    bulk: 'Dökme',
    bags25kg: '25kg Torbalar',
    bigBags1Mt: '1Mt Büyük Torbalar',
    component: 'Bileşen',
    concentrate: 'Konsantre',
    lump: 'Yumru',
    sulfuricAcidProduction: 'Sülfürik Asit Üretimi',
    whyChooseOurIronPyrite: 'Neden Bizim Demir Piritimizi Seçmelisiniz?',
    onlyProducerInTurkey: 'Türkiye\'deki Tek Üretici',
    uniqueMarketPositionReliableSupply: 'Güvenilir tedarik zinciri ve kalite güvencesi ile benzersiz pazar konumu.',
    nearGemlikPortOptimizedLogistics: 'Dünya çapında optimize edilmiş lojistik ve uygun maliyetli nakliye için Gemlik Limanı yakınında.',
    consistentQualityReliableSpecs: 'Uluslararası standartları karşılayan güvenilir özelliklerle tutarlı kalite.',
    premiumQuality: 'Premium Kalite',
    multipleSizes: 'Çoklu Boyutlar',

    // Olivine Specific - Turkish
    olivineOverview: 'Döküm, kumlama, refraktör ve cüruf koşullandırması dahil farklı uygulamalar için en iyi kaliteli Olivinlerden birini tedarik ediyoruz.',
    bestQuality: 'En İyi Kalite',
    multipleApplications: 'Çoklu Uygulamalar',
    slagSand: 'Cüruf Kumu',
    highMeltingPoint: 'Yüksek Erime Noktası',
    hardness: 'Sertlik',
    density: 'Yoğunluk',
    chemicalStability: 'Kimyasal Stabilite',
    excellent: 'Mükemmel',
    refractoryIndustry: 'Refraktör Endüstrisi',
    blastingApplications: 'Kumlama Uygulamaları',
    olivineFoundryApp: 'Döküm kalıplama ve kor yapımı uygulamaları için mükemmel termal özellikler.',
    olivineRefractoryApp: 'Refraktör sprey uygulamaları için yüksek erime noktası ve kimyasal stabilite.',
    olivineSteelApp: 'Çelik fabrikası uygulamaları için üstün cüruf koşullandırma özellikleri.',
    olivineBlastingApp: 'Yüzey hazırlama ve temizleme için çevre dostu aşındırıcı.',
    whyChooseOurOlivine: 'Neden Bizim Olivinimizi Seçmelisiniz?',
    superiorQuality: 'Üstün Kalite',
    olivineSuperiorDesc: 'Tutarlı özelliklerle Türk madenlerinden kaynaklanan en yüksek kaliteli olivin.',
    versatileApplications: 'Çok Yönlü Uygulamalar',
    olivineVersatileDesc: 'Döküm, refraktör, kumlama ve çelik endüstrisi uygulamaları için uygundur.',
    reliableSupply: 'Güvenilir Tedarik',
    olivineReliableDesc: 'Dünya çapında teslimat için stratejik konum avantajları ile tutarlı tedarik zinciri.',

    // Manganese Specific - Turkish
    manganeseOverview: 'Metalurji, kimyasal ve batarya üretimi uygulamaları için çeşitli manganez bileşikleri mevcuttur.',
    multipleForms: 'Çoklu Formlar',
    ferroAlloyProduction: 'Ferro Alaşım Üretimi',
    chemicalComposition: 'Kimyasal Kompozisyon',
    manganeseChemicalDesc: 'Çeşitli endüstriyel uygulamalar için tutarlı kimyasal kompozisyona sahip yüksek kaliteli manganez bileşikleri.',
    particleSize: 'Partikül Boyutu',
    manganeseParticleSizeDesc: 'Belirli uygulama gereksinimlerini karşılamak için çeşitli partikül boyutlarında mevcuttur.',
    qualityStandards: 'Kalite Standartları',
    manganeseQualityDesc: 'Sertifikalı özelliklerle uluslararası kalite standartlarına uygunluk.',
    whyChooseOurManganese: 'Neden Bizim Manganezimizi Seçmelisiniz?',
    consistentQuality: 'Tutarlı Kalite',
    manganeseConsistentDesc: 'Tutarlı kimyasal kompozisyon ve özelliklerle güvenilir kalite standartları.',
    manganeseMultipleDesc: 'Mn3O4, ferro manganez ve oksit bileşikleri dahil çeşitli formlarda mevcuttur.',
    manganeseReliableDesc: 'Stratejik tedarik ve kalite güvence programları ile güvenilir tedarik zinciri.',

    // Chromite Sand Specific - Turkish
    superiorFinish: 'Üstün Yüzey',
    chromiteSandOverview: 'Mükemmel yüzey kalitesi ve azaltılmış döküm hataları sağlayan döküm uygulamaları için yüksek kaliteli kromit kumu.',
    reducedCastingDefects: 'Azaltılmış Döküm Hataları',
    highThermalConductivity: 'Yüksek Termal İletkenlik',
    foundryMoldingSand: 'Döküm Kalıplama Kumu',
    coreMaking: 'Kor Yapımı',
    pigmentProduction: 'Pigment Üretimi',
    meltingPoint: 'Erime Noktası',
    thermalExpansion: 'Termal Genleşme',
    low: 'Düşük',
    chromiteSandOrigin: 'Tutarlı mineral kompozisyona sahip yüksek kaliteli kromit yataklarından temin edilir.',
    chromiteSandSupply: 'Dünya çapında güvenilir teslimat sağlayan stratejik tedarik zinciri yönetimi.',
    whyChooseOurChromiteSand: 'Neden Bizim Kromit Kumumuzu Seçmelisiniz?',
    chromiteSandQualityDesc: 'Döküm uygulamaları için mükemmel termal özellikler ile üstün kalite kromit kumu.',
    betterCastingResults: 'Daha İyi Döküm Sonuçları',
    chromiteSandResultsDesc: 'Döküm uygulamalarında gelişmiş yüzey kalitesi ve azaltılmış hatalar.',
    directSupply: 'Doğrudan Tedarik',
    chromiteSandSupplyDesc: 'Uygun maliyetli fiyatlandırma ve güvenilir kalite sağlayan madenlerden doğrudan tedarik.',

    // Fluorspar Specific - Turkish
    fluxingAgent: 'Akıştırıcı Madde',
    southAfricanOrigin: 'Güney Afrika Menşei',
    fluorsparOverview: 'Güney Afrika madenlerinden premium kalite florit, metalurjik uygulamalar için etkili akıştırıcı madde olarak hizmet verir.',
    acidGrade: 'Asit Kalitesi',
    metallurgicalGrade: 'Metalurjik Kalite',
    ceramicGrade: 'Seramik Kalitesi',
    calciumFluoride: 'Kalsiyum Florür',
    republicOfSouthAfricaOrigin: 'Güney Afrika Cumhuriyeti Menşei',
    stainlessSteelProduction: 'Paslanmaz Çelik Üretimi',
    fluorsparSteelApp: 'Çelik üretimi için etkili akıştırıcı madde, erime sıcaklığını düşürür.',
    fluorsparStainlessApp: 'Cüruf akışkanlığını geliştirerek paslanmaz çelik üretimi için gereklidir.',
    fluorsparFerroApp: 'Gelişmiş verimlilik için ferro alaşım üretiminde kritik bileşen.',
    fluorsparBaseMetalsApp: 'Daha iyi metal geri kazanımı için baz metal arıtma süreçlerinde kullanılır.',
    fluorsparAluminumApp: 'Enerji tüketimini azaltarak alüminyum eritme için gereklidir.',
    caf2Content: 'CaF2 İçeriği',
    whyChooseOurFluorspar: 'Neden Bizim Floritimizi Seçmelisiniz?',
    southAfricanQuality: 'Güney Afrika Kalitesi',
    fluorsparQualityDesc: 'Yüksek CaF2 içeriği ile Güney Afrika madenlerinden premium kalite florit.',
    multipleGrades: 'Çoklu Kaliteler',
    fluorsparGradesDesc: 'Çeşitli uygulamalar için asit, metalurjik ve seramik kalitelerinde mevcuttur.',
    consistentSupply: 'Tutarlı Tedarik',
    fluorsparSupplyDesc: 'Tutarlı kalite ve güvenilir tedarik ile desteklenmektedir.',

    // Soda Ash Specific - Turkish (devamı)
    sodaAshSupplyDesc: 'Güney Afrika kaynaklarından tutarlı kalite sağlayan güvenilir tedarik zinciri.',
    turkishOrigin: 'Türk Menşei',
    sodaAshOverview: 'Cam, kimyasal ve deterjan endüstrisi uygulamaları için Türk kaynaklarından yüksek kaliteli soda külü.',
    denseSodaAsh: 'Yoğun Soda Külü',
    lightSodaAsh: 'Hafif Soda Külü',
    sodiumCarbonate: 'Sodyum Karbonat',
    clearColorlessAqueousSolution: 'Berrak, renksiz sulu çözelti',
    soapDetergentIndustry: 'Sabun ve Deterjan Endüstrisi',
    paperProduction: 'Kağıt Üretimi',
    sodaAshGlassApp: 'Erime sıcaklığını düşüren cam üretimi için temel hammadde.',
    sodaAshChemicalApp: 'Çeşitli endüstriyel işlemler için kimyasal üretimde ana bileşen.',
    sodaAshSoapApp: 'Alkalilik için sabun ve deterjan üretiminde kritik bileşen.',
    sodaAshPaperApp: 'Hamur hazırlama ve ağartma işlemleri için kağıt üretiminde kullanılır.',
    sodaAshWaterApp: 'pH ayarlaması ve yumuşatma için su arıtma uygulamaları.',
    sodiumBicarbonate: 'Sodyum Bikarbonat',
    sodiumBicarbonateDesc: 'Gıda, yem ve teknik kalitelerde mevcut yüksek kaliteli sodyum bikarbonat.',
    foodGrade: 'Gıda Kalitesi',
    feedGrade: 'Yem Kalitesi',
    technicalGrade: 'Teknik Kalite',
    whyChooseOurSodaAsh: 'Neden Bizim Soda Külümüzü Seçmelisiniz?',
    sodaAshOriginDesc: 'Tutarlı özelliklerle güvenilir Türk kaynaklarından yüksek kaliteli soda külü.',
    sodaAshAppsDesc: 'Cam, kimyasal, deterjan ve kağıt endüstrisi uygulamaları için uygundur.',
    sodaAshQualityDesc: 'Uluslararası standartları karşılayan güvenilir özelliklerle tutarlı kalite.',

    // Sulphur Specific - Turkish
    sulphurOverview: 'Kimyasal, gübre ve kauçuk endüstrisi uygulamaları için çeşitli formlarda yüksek saflıkta kükürt.',
    granular: 'Granüler',
    appearance: 'Görünüm',
    brightYellow: 'Parlak Sarı',
    texture: 'Doku',
    softPowder: 'Yumuşak Toz',
    purity: 'Saflık',
    highGrade: 'Yüksek Kalite',
    pharmaceutical: 'Eczacılık',
    sulphurChemicalApp: 'Sülfürik asit üretimi ve çeşitli kimyasal işlemler için gereklidir.',
    sulphurFertilizerApp: 'Toprak asitlendirmesi için gübre üretiminde ana bileşen.',
    sulphurRubberApp: 'Elastikiyet ve dayanıklılığı artıran kauçuk vulkanizasyonu için kritiktir.',
    sulphurPharmaApp: 'Topikal tedaviler ve ilaçlarda farmasötik uygulamalar.',
    sulphurContent: 'Kükürt İçeriği',
    moisture: 'Nem',
    ashContent: 'Kül İçeriği',
    various: 'Çeşitli',
    whyChooseOurSulphur: 'Neden Bizim Kükürdümüzü Seçmelisiniz?',
    sulphurHighPurityDesc: 'Endüstriyel uygulamalar için minimum %99.5 içeriğe sahip yüksek saflıkta kükürt.',
    sulphurConsistentDesc: 'Güvenilir özellikler ve sertifikalı analiz ile tutarlı kalite.',
    sulphurMultipleFormsDesc: 'Çeşitli uygulamalar için toz, granüler ve yumru formlarında mevcuttur.',

    // Water Treatment Specific - Turkish
    mediaFilter: 'Medya Filtresi',
    highPerformance: 'Yüksek Performans',
    waterTreatmentOverview: 'Etkili su arıtma ve arıtma uygulamaları için manganez dioksit medya filtresi.',
    manganeseDioxide: 'Manganez Dioksit',
    variousGrades: 'Çeşitli Kaliteler',
    ironManganeseRemoval: 'Demir ve Manganez Giderimi',
    hydrogenSulfideReduction: 'Hidrojen Sülfür Azaltma',
    tasteOdorImprovement: 'Tat ve Koku İyileştirmesi',
    longServiceLife: 'Uzun Hizmet Ömrü',
    lowMaintenance: 'Düşük Bakım',
    municipalWaterTreatment: 'Belediye Su Arıtma',
    industrialWaterProcessing: 'Endüstriyel Su İşleme',
    wellWaterTreatment: 'Kuyu Suyu Arıtma',
    waterMunicipalApp: 'Demir ve manganez giderimi için belediye su arıtma sistemleri için etkilidir.',
    waterIndustrialApp: 'Kalite iyileştirmesi için endüstriyel su işleme uygulamaları.',
    waterWellApp: 'Konut ve ticari uygulamalar için kuyu suyu arıtma.',
    waterFiltrationApp: 'Kapsamlı su arıtma için gelişmiş filtrasyon sistemleri.',
    phRange: 'pH Aralığı',
    porosity: 'Gözeneklilik',
    high: 'Yüksek',
    whyChooseOurWaterTreatment: 'Neden Bizim Su Arıtma Ürünlerimizi Seçmelisiniz?',
    effectiveFiltration: 'Etkili Filtrasyon',
    waterEffectiveDesc: 'Kapsamlı su arıtma için son derece etkili filtrasyon medyası.',
    costEffective: 'Uygun Maliyetli',
    waterCostDesc: 'Uzun hizmet ömrü ve düşük bakım gereksinimleri ile uygun maliyetli çözüm.',
    reliablePerformance: 'Güvenilir Performans',
    waterReliableDesc: 'Güvenilir kirletici giderim yetenekleri ile tutarlı performans.',

    // Additional missing keys - Turkish
    unique: 'Benzersiz',
    ironPyriteProducer: 'Demir Piriti Üreticisi',
    steelIndustry: 'Çelik Endüstrisi',
    steelProduction: 'Çelik Üretimi'
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}